// Code generated by protoc-gen-go.
// source: todo.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	TodoRequest
	TodoResponse
	TodosResponse
	AllRequest
	CreateRequest
	FindRequest
	UpdateRequest
	DeleteRequest
	DeleteResponse
	DeleteAllRequest
	DeleteAllResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoRequest struct {
	Title     string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
}

func (m *TodoRequest) Reset()                    { *m = TodoRequest{} }
func (m *TodoRequest) String() string            { return proto.CompactTextString(m) }
func (*TodoRequest) ProtoMessage()               {}
func (*TodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TodoResponse struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed" json:"completed,omitempty"`
}

func (m *TodoResponse) Reset()                    { *m = TodoResponse{} }
func (m *TodoResponse) String() string            { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()               {}
func (*TodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TodosResponse struct {
	Todos []*TodoResponse `protobuf:"bytes,1,rep,name=todos" json:"todos,omitempty"`
}

func (m *TodosResponse) Reset()                    { *m = TodosResponse{} }
func (m *TodosResponse) String() string            { return proto.CompactTextString(m) }
func (*TodosResponse) ProtoMessage()               {}
func (*TodosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TodosResponse) GetTodos() []*TodoResponse {
	if m != nil {
		return m.Todos
	}
	return nil
}

type AllRequest struct {
}

func (m *AllRequest) Reset()                    { *m = AllRequest{} }
func (m *AllRequest) String() string            { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()               {}
func (*AllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateRequest struct {
	Todo *TodoRequest `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateRequest) GetTodo() *TodoRequest {
	if m != nil {
		return m.Todo
	}
	return nil
}

type FindRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *FindRequest) Reset()                    { *m = FindRequest{} }
func (m *FindRequest) String() string            { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()               {}
func (*FindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UpdateRequest struct {
	Id   int64        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Todo *TodoRequest `protobuf:"bytes,2,opt,name=todo" json:"todo,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateRequest) GetTodo() *TodoRequest {
	if m != nil {
		return m.Todo
	}
	return nil
}

type DeleteRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteResponse struct {
	Error string        `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Todo  *TodoResponse `protobuf:"bytes,2,opt,name=todo" json:"todo,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteResponse) GetTodo() *TodoResponse {
	if m != nil {
		return m.Todo
	}
	return nil
}

type DeleteAllRequest struct {
}

func (m *DeleteAllRequest) Reset()                    { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()               {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteAllResponse struct {
}

func (m *DeleteAllResponse) Reset()                    { *m = DeleteAllResponse{} }
func (m *DeleteAllResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAllResponse) ProtoMessage()               {}
func (*DeleteAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*TodoRequest)(nil), "pb.TodoRequest")
	proto.RegisterType((*TodoResponse)(nil), "pb.TodoResponse")
	proto.RegisterType((*TodosResponse)(nil), "pb.TodosResponse")
	proto.RegisterType((*AllRequest)(nil), "pb.AllRequest")
	proto.RegisterType((*CreateRequest)(nil), "pb.CreateRequest")
	proto.RegisterType((*FindRequest)(nil), "pb.FindRequest")
	proto.RegisterType((*UpdateRequest)(nil), "pb.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "pb.DeleteResponse")
	proto.RegisterType((*DeleteAllRequest)(nil), "pb.DeleteAllRequest")
	proto.RegisterType((*DeleteAllResponse)(nil), "pb.DeleteAllResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Todo service

type TodoClient interface {
	All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*TodosResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*TodosResponse, error) {
	out := new(TodosResponse)
	err := grpc.Invoke(ctx, "/pb.Todo/All", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/pb.Todo/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/pb.Todo/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/pb.Todo/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*DeleteAllResponse, error) {
	out := new(DeleteAllResponse)
	err := grpc.Invoke(ctx, "/pb.Todo/DeleteAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/pb.Todo/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Todo service

type TodoServer interface {
	All(context.Context, *AllRequest) (*TodosResponse, error)
	Create(context.Context, *CreateRequest) (*TodoResponse, error)
	Find(context.Context, *FindRequest) (*TodoResponse, error)
	Update(context.Context, *UpdateRequest) (*TodoResponse, error)
	DeleteAll(context.Context, *DeleteAllRequest) (*DeleteAllResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).All(ctx, req.(*AllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).DeleteAll(ctx, req.(*DeleteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _Todo_All_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Todo_Create_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _Todo_Find_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Todo_Update_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _Todo_DeleteAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Todo_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x93, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0x76, 0x2b, 0xee, 0x74, 0x9d, 0xdb, 0x71, 0xc2, 0x28, 0x8a, 0x23, 0x8a, 0x0c,
	0x85, 0x0d, 0xa7, 0x20, 0x78, 0x37, 0x1c, 0x5e, 0x79, 0x15, 0xf4, 0x01, 0x9c, 0xc9, 0x45, 0xa1,
	0x2e, 0xb5, 0x8d, 0xef, 0xe5, 0x23, 0x4a, 0x92, 0xa5, 0xff, 0xb6, 0x79, 0xd9, 0xf3, 0xe7, 0xf7,
	0xe5, 0xfb, 0x0e, 0x05, 0x90, 0x82, 0x89, 0x59, 0x9a, 0x09, 0x29, 0xd0, 0x4d, 0xd7, 0x64, 0x09,
	0xc1, 0x9b, 0x60, 0x82, 0xf2, 0xef, 0x1f, 0x9e, 0x4b, 0x1c, 0x41, 0x47, 0xc6, 0x32, 0xe1, 0x63,
	0x67, 0xe2, 0x4c, 0xbb, 0xd4, 0x7c, 0xe0, 0x19, 0x74, 0x3f, 0xc5, 0x57, 0x9a, 0x70, 0xc9, 0xd9,
	0xd8, 0x9d, 0x38, 0xd3, 0x23, 0x5a, 0x16, 0x08, 0x85, 0x9e, 0x41, 0xe4, 0xa9, 0xd8, 0xe4, 0x1c,
	0xfb, 0xe0, 0xc6, 0x4c, 0x03, 0x3c, 0xea, 0xc6, 0xac, 0x64, 0xba, 0x07, 0x99, 0x5e, 0x93, 0xf9,
	0x08, 0xa1, 0x62, 0xe6, 0x05, 0xf4, 0x1a, 0x3a, 0xea, 0xe5, 0xf9, 0xd8, 0x99, 0x78, 0xd3, 0x60,
	0x31, 0x98, 0xa5, 0xeb, 0x59, 0x55, 0x95, 0x9a, 0x36, 0xe9, 0x01, 0x2c, 0x93, 0x64, 0x6b, 0x87,
	0x3c, 0x40, 0xf8, 0x9c, 0xf1, 0x0f, 0xc9, 0xad, 0xbf, 0x4b, 0x68, 0xab, 0x39, 0xfd, 0xba, 0x60,
	0x71, 0x5c, 0x52, 0x74, 0x9b, 0xea, 0x26, 0x39, 0x87, 0xe0, 0x25, 0xde, 0x30, 0xbb, 0xd3, 0xf0,
	0x43, 0x56, 0x10, 0xbe, 0xa7, 0xac, 0x02, 0x6d, 0x1a, 0xb6, 0x22, 0xee, 0x7f, 0x22, 0x17, 0x10,
	0xae, 0xb8, 0x32, 0x7b, 0x48, 0xe6, 0x15, 0xfa, 0x76, 0x60, 0x9b, 0xc1, 0x08, 0x3a, 0x3c, 0xcb,
	0x44, 0x66, 0x8f, 0xa3, 0x3f, 0xf0, 0xaa, 0xa6, 0xb6, 0x1b, 0x8c, 0x91, 0x43, 0x18, 0x18, 0x5a,
	0x25, 0x9d, 0x13, 0x18, 0x56, 0x6a, 0x66, 0x7c, 0xf1, 0xeb, 0x42, 0x5b, 0xed, 0xe3, 0x0d, 0x78,
	0xcb, 0x24, 0xc1, 0xbe, 0x02, 0x96, 0x4b, 0xd1, 0xd0, 0x0a, 0x14, 0xb7, 0x21, 0x2d, 0x9c, 0x83,
	0x6f, 0x72, 0x46, 0xdd, 0xae, 0x65, 0x1e, 0xed, 0x3c, 0x89, 0xb4, 0xf0, 0x16, 0xda, 0x2a, 0x62,
	0xd4, 0xe1, 0x54, 0xc2, 0xde, 0x3b, 0x3c, 0x07, 0xdf, 0x04, 0x6e, 0xe8, 0xb5, 0xf0, 0xf7, 0x2e,
	0x3c, 0x41, 0xb7, 0x30, 0x86, 0x23, 0x35, 0xd0, 0xf4, 0x1e, 0x9d, 0x36, 0xaa, 0xc5, 0xee, 0x1d,
	0xf8, 0xa6, 0x6c, 0xc4, 0x6a, 0x37, 0x8a, 0xb0, 0x5a, 0xb2, 0x2b, 0x6b, 0x5f, 0xff, 0x4e, 0xf7,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x0f, 0xf7, 0x36, 0x5c, 0x03, 0x00, 0x00,
}
