/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.pb.TodosResponse');

goog.require('jspb.Message');
goog.require('proto.pb.TodoResponse');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.TodosResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.TodosResponse.repeatedFields_, null);
};
goog.inherits(proto.pb.TodosResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.TodosResponse.displayName = 'proto.pb.TodosResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.TodosResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.TodosResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.TodosResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.TodosResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.TodosResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    todosList: jspb.Message.toObjectList(msg.getTodosList(),
    proto.pb.TodoResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.TodosResponse} The clone.
 */
proto.pb.TodosResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.TodosResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated TodoResponse todos = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.pb.TodoResponse>}
 */
proto.pb.TodosResponse.prototype.getTodosList = function() {
  return /** @type{!Array.<!proto.pb.TodoResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.TodoResponse, 1));
};


/** @param {Array.<!proto.pb.TodoResponse>|undefined} value  */
proto.pb.TodosResponse.prototype.setTodosList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.pb.TodosResponse.prototype.clearTodosList = function() {
  this.setTodosList([]);
};


