# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todo.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\ntodo.proto\x12\x02pb\"/\n\x0bTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"<\n\x0cTodoResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"0\n\rTodosResponse\x12\x1f\n\x05todos\x18\x01 \x03(\x0b\x32\x10.pb.TodoResponse\"\x0c\n\nAllRequest\".\n\rCreateRequest\x12\x1d\n\x04todo\x18\x01 \x01(\x0b\x32\x0f.pb.TodoRequest\"\x19\n\x0b\x46indRequest\x12\n\n\x02id\x18\x01 \x01(\x03\":\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1d\n\x04todo\x18\x02 \x01(\x0b\x32\x0f.pb.TodoRequest\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"?\n\x0e\x44\x65leteResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x1e\n\x04todo\x18\x02 \x01(\x0b\x32\x10.pb.TodoResponse\"\x12\n\x10\x44\x65leteAllRequest\"\x13\n\x11\x44\x65leteAllResponse2\xb0\x02\n\x04Todo\x12*\n\x03\x41ll\x12\x0e.pb.AllRequest\x1a\x11.pb.TodosResponse\"\x00\x12/\n\x06\x43reate\x12\x11.pb.CreateRequest\x1a\x10.pb.TodoResponse\"\x00\x12+\n\x04\x46ind\x12\x0f.pb.FindRequest\x1a\x10.pb.TodoResponse\"\x00\x12/\n\x06Update\x12\x11.pb.UpdateRequest\x1a\x10.pb.TodoResponse\"\x00\x12:\n\tDeleteAll\x12\x14.pb.DeleteAllRequest\x1a\x15.pb.DeleteAllResponse\"\x00\x12\x31\n\x06\x44\x65lete\x12\x11.pb.DeleteRequest\x1a\x12.pb.DeleteResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TODOREQUEST = _descriptor.Descriptor(
  name='TodoRequest',
  full_name='pb.TodoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='pb.TodoRequest.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='completed', full_name='pb.TodoRequest.completed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=65,
)


_TODORESPONSE = _descriptor.Descriptor(
  name='TodoResponse',
  full_name='pb.TodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.TodoResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='pb.TodoResponse.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='completed', full_name='pb.TodoResponse.completed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=127,
)


_TODOSRESPONSE = _descriptor.Descriptor(
  name='TodosResponse',
  full_name='pb.TodosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todos', full_name='pb.TodosResponse.todos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=177,
)


_ALLREQUEST = _descriptor.Descriptor(
  name='AllRequest',
  full_name='pb.AllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=191,
)


_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='pb.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='pb.CreateRequest.todo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=239,
)


_FINDREQUEST = _descriptor.Descriptor(
  name='FindRequest',
  full_name='pb.FindRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.FindRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=266,
)


_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='pb.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.UpdateRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='todo', full_name='pb.UpdateRequest.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=326,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='pb.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.DeleteRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=355,
)


_DELETERESPONSE = _descriptor.Descriptor(
  name='DeleteResponse',
  full_name='pb.DeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='pb.DeleteResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='todo', full_name='pb.DeleteResponse.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=420,
)


_DELETEALLREQUEST = _descriptor.Descriptor(
  name='DeleteAllRequest',
  full_name='pb.DeleteAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=440,
)


_DELETEALLRESPONSE = _descriptor.Descriptor(
  name='DeleteAllResponse',
  full_name='pb.DeleteAllResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=461,
)

_TODOSRESPONSE.fields_by_name['todos'].message_type = _TODORESPONSE
_CREATEREQUEST.fields_by_name['todo'].message_type = _TODOREQUEST
_UPDATEREQUEST.fields_by_name['todo'].message_type = _TODOREQUEST
_DELETERESPONSE.fields_by_name['todo'].message_type = _TODORESPONSE
DESCRIPTOR.message_types_by_name['TodoRequest'] = _TODOREQUEST
DESCRIPTOR.message_types_by_name['TodoResponse'] = _TODORESPONSE
DESCRIPTOR.message_types_by_name['TodosResponse'] = _TODOSRESPONSE
DESCRIPTOR.message_types_by_name['AllRequest'] = _ALLREQUEST
DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['FindRequest'] = _FINDREQUEST
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
DESCRIPTOR.message_types_by_name['DeleteResponse'] = _DELETERESPONSE
DESCRIPTOR.message_types_by_name['DeleteAllRequest'] = _DELETEALLREQUEST
DESCRIPTOR.message_types_by_name['DeleteAllResponse'] = _DELETEALLRESPONSE

TodoRequest = _reflection.GeneratedProtocolMessageType('TodoRequest', (_message.Message,), dict(
  DESCRIPTOR = _TODOREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.TodoRequest)
  ))
_sym_db.RegisterMessage(TodoRequest)

TodoResponse = _reflection.GeneratedProtocolMessageType('TodoResponse', (_message.Message,), dict(
  DESCRIPTOR = _TODORESPONSE,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.TodoResponse)
  ))
_sym_db.RegisterMessage(TodoResponse)

TodosResponse = _reflection.GeneratedProtocolMessageType('TodosResponse', (_message.Message,), dict(
  DESCRIPTOR = _TODOSRESPONSE,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.TodosResponse)
  ))
_sym_db.RegisterMessage(TodosResponse)

AllRequest = _reflection.GeneratedProtocolMessageType('AllRequest', (_message.Message,), dict(
  DESCRIPTOR = _ALLREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.AllRequest)
  ))
_sym_db.RegisterMessage(AllRequest)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.CreateRequest)
  ))
_sym_db.RegisterMessage(CreateRequest)

FindRequest = _reflection.GeneratedProtocolMessageType('FindRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.FindRequest)
  ))
_sym_db.RegisterMessage(FindRequest)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.UpdateRequest)
  ))
_sym_db.RegisterMessage(UpdateRequest)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.DeleteRequest)
  ))
_sym_db.RegisterMessage(DeleteRequest)

DeleteResponse = _reflection.GeneratedProtocolMessageType('DeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETERESPONSE,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.DeleteResponse)
  ))
_sym_db.RegisterMessage(DeleteResponse)

DeleteAllRequest = _reflection.GeneratedProtocolMessageType('DeleteAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEALLREQUEST,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.DeleteAllRequest)
  ))
_sym_db.RegisterMessage(DeleteAllRequest)

DeleteAllResponse = _reflection.GeneratedProtocolMessageType('DeleteAllResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETEALLRESPONSE,
  __module__ = 'todo_pb2'
  # @@protoc_insertion_point(class_scope:pb.DeleteAllResponse)
  ))
_sym_db.RegisterMessage(DeleteAllResponse)


# @@protoc_insertion_point(module_scope)
