/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.pb.UpdateRequest');

goog.require('jspb.Message');
goog.require('proto.pb.TodoRequest');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.UpdateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.UpdateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.UpdateRequest.displayName = 'proto.pb.UpdateRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.UpdateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.UpdateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.UpdateRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.UpdateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId(),
    todo: (f = msg.getTodo()) && proto.pb.TodoRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.UpdateRequest} The clone.
 */
proto.pb.UpdateRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.UpdateRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.pb.UpdateRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.pb.UpdateRequest.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional TodoRequest todo = 2;
 * @return {proto.pb.TodoRequest}
 */
proto.pb.UpdateRequest.prototype.getTodo = function() {
  return /** @type{proto.pb.TodoRequest} */ (
    jspb.Message.getWrapperField(this, proto.pb.TodoRequest, 2));
};


/** @param {proto.pb.TodoRequest|undefined} value  */
proto.pb.UpdateRequest.prototype.setTodo = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.pb.UpdateRequest.prototype.clearTodo = function() {
  this.setTodo(undefined);
};


